version: "3"

services:
  fleetManagement:
    image: postgres:16.1-alpine3.19
    container_name: fleet-management
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
